[project]
name = "peterbouda-eu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ghp-import>=2.1.0",
    "langdetect>=1.0.9",
    "markdown>=3.7",
    "pelican>=4.11.0",
    "typogrify>=2.1.0",
]
